Response {
    status: 200,
    statusText: 'OK',
    headers: Headers {
      'content-type': 'application/json;charset=UTF-8',
      'content-length': '1578',
      connection: 'keep-alive',
      date: 'Tue, 15 Apr 2025 18:43:16 GMT',
      'access-control-allow-methods': 'GET, HEAD, OPTIONS',
      server: 'nginx',
      'x-mbx-uuid': 'ab1bdc11-ee65-4c75-972e-b7771d7804c0',
      'x-mbx-used-weight': '2',
      'x-mbx-used-weight-1m': '2',
      'content-encoding': 'gzip',
      'strict-transport-security': 'max-age=31536000; includeSubdomains',
      'x-frame-options': 'SAMEORIGIN',
      'x-xss-protection': '1; mode=block',
      'x-content-type-options': 'nosniff',
      'content-security-policy': "default-src 'self'",
      'x-content-security-policy': "default-src 'self'",
      'x-webkit-csp': "default-src 'self'",
      'cache-control': 'no-cache, no-store, must-revalidate',
      pragma: 'no-cache',
      expires: '0',
      'access-control-allow-origin': '*',
      'x-cache': 'Miss from cloudfront',
      via: '1.1 d2c6479bc16b046bb090d1c0f2be5140.cloudfront.net (CloudFront)',
      'x-amz-cf-pop': 'OTP50-P2',
      'x-amz-cf-id': 'EUzWuL0NcH2F2hTn_LcgUd4IldZk-G7SMMHvM2nHQnawW4p9FI0_lQ=='
    },
    body: ReadableStream { locked: false, state: 'readable', supportsBYOB: true },
    bodyUsed: false,
    ok: true,
    redirected: false,
    type: 'basic',
    url: 'https://api.binance.com/api/v3/klines?symbol=SOLUSDT&interval=1h&limit=30'
  }