name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]


jobs:
    build:
        name: Node.js App
        runs-on: ubuntu-latest
        steps: 
            - name: checkout code
              uses: actions/checkout@v3
            - name: install node.js
              uses: actions/setup-node@v3
              with: 
                node-version: 22
            - name: install dependecies
              run: npm install
            - name: test lint
              run: npm run lint 