name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
jobs:
    node-bot-test:
        runs-on: ubuntu-latest

        steps:
            - name: checkout code
              uses: actions/checkout@v3
            - name: install node.js
              uses: actions/setup-node@v3
              with:
                node-version: 22
            - name: install dependencies
              run: npm install
            - name: Run linter
              run: npm run lint
            - name: Run test
              run: npm run test